#!/bin/sh
# ------------------------------------------------------------------------------
#
#PBS -A <PROJECT_ID>
#PBS -N tpose_optim
#PBS -j oe
#PBS -q main
#PBS -l walltime=01:00:00
#PBS -l select=1:ncpus=128:mpiprocs=1

## load modules (compiler, MPI, etc.)
module --force  purge
module load ncarenv/23.09 intel/2023.2.1 intel-mpi/2021.10.0
module list

cd /glade/work/edavenport/assim/tpose/opti/

cp /glade/work/edavenport/assim/tpose/sep2012/run_ad/ecco* .
cp /glade/work/edavenport/optim_m1qn3/src/optim.x .

#limit stacksize unlimited
mpirun -n 1 ./optim.x > output.txt
